# Generated by Django 5.0.7 on 2024-08-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_alter_county_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='county',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='County',
        ),
    ]
