# Generated by Django 5.0.7 on 2024-08-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_alter_districts_county_delete_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=10)),
                ('districts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corona.districts')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corona.states')),
            ],
        ),
    ]
