# Generated by Django 5.0.7 on 2024-09-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_rename_districts_towns_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='abbreviation',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='states',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
