# Generated by Django 5.0.7 on 2024-09-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_alter_states_abbreviation_alter_states_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
