# Generated by Django 5.0.7 on 2024-09-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0007_alter_towns_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towns',
            name='id',
        ),
        migrations.AlterField(
            model_name='towns',
            name='plz',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
